name: Publish Python Package

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    quality-assurance:
        uses: davyddd/dd-lib-stub/.github/workflows/quality_assurance.yml@v0.0.4
        with:
            package-name: ddutils
            test-matrix: '{"python-version": ["3.11", "3.12", "3.13", "3.14"]}'
            default-python-version: '3.14'
            upload-coverage: true
        secrets: inherit
    publish:
        needs: quality-assurance
        uses: davyddd/dd-lib-stub/.github/workflows/publish_python_package.yml@v0.0.4
        with:
            package-name: ddutils
            python-version: '3.14'
        permissions:
            contents: write
            id-token: write
