name: Quality Assurance

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    quality-assurance:
        uses: davyddd/dd-lib-stub/.github/workflows/quality_assurance.yml@v0.0.2
        with:
            package-name: ddutils
            test-matrix: '{"python-version": ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]}'
            default-python-version: '3.14'
            upload-coverage: ${{ github.event_name == 'push' }}
        secrets: inherit
