name: Quality Assurance

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    linters:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                command: [
                    "ruff . --config ruff.toml",
                    "ruff format . --check --config ruff.toml",
                    "mypy --config mypy.toml"
                ]
        steps:
            -   uses: actions/checkout@v4.1.1
            -   uses: ./.github/actions/setup_python_and_poetry
            -   uses: ./.github/actions/linters
                with:
                    command: ${{ matrix.command }}
    tests:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                python-version: [ "3.8" ]
        steps:
            -   uses: actions/checkout@v4.1.1
            -   uses: ./.github/actions/setup_python_and_poetry
                with:
                    python-version: ${{ matrix.python-version }}
            -   uses: ./.github/actions/tests
